# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba4a61939e3f8339c96d4af26477c254"
name = "variant-image-automator"
application_url = "https://covered-pb-door-fc.trycloudflare.com"
embedded = true
handle = "variant-image-automator-3"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://covered-pb-door-fc.trycloudflare.com/auth/callback", "https://covered-pb-door-fc.trycloudflare.com/auth/shopify/callback", "https://covered-pb-door-fc.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
